services:
  - name: university-recommender-api
    type: web
    plan: starter
    region: singapore
    buildCommand: pip install -r gateway/requirements.txt
    startCommand: cd gateway && uvicorn main:app --host 0.0.0.0 --port $PORT
    runtime: python
    envVars:
      - key: ENVIRONMENT
        value: production
      - key: ALGORITHM
        value: HS256
      - key: ALLOWED_ORIGINS
        sync: false
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_KEY
        sync: false
      - key: SECRET_KEY
        sync: false
      - key: JAMAIBASE_PROJECT_ID
        sync: false
      - key: JAMAIBASE_PAT
        sync: false